### ISSUE TITLE
no src.zip in asset dir

### ISSUE THREAD

**Issue by colordancer** [Tribler/self-compile-Android#3]
Hi, 

From my understanding, before re-compilation, the original Apk should be extracted and de-compiled first. But I failed to find such logic. I only found the CleanTask function triggered by Reset button.

But what's confusing me then is CleanTask only drops some Zip archives in asset directory, instead of targeting the App's installation package. So, if I want to make my App self-compile, should I add some similar source packages into the asset directory? What I thought and hope is dynamically operate the installation package.

**Comment by whirm** [comment]
@synctext is there anybody that can answer questions about this project?

**Comment by brussee** [comment]
> From my understanding, before re-compilation, the original Apk should be extracted and de-compiled first.

This app can self-compile, meaning compile from source (repeatedly), not de-compile from binaries.

> CleanTask only drops some Zip archives in asset directory

CleanTask unzips the source files and dependencies that are to be compiled and packaged into an apk.

> So, if I want to make my App self-compile, should I add some similar source packages into the asset directory?

You should copy your source and libs, etc. files in the appropriate .zip files (naming scheme speaks for itself) and put those in the assets folder.
Look at the function buildApk() in BuildTask.java for more information.

**Comment by whirm** [comment]
Thanks!
