### ISSUE TITLE
can you support the libs

### ISSUE THREAD

**Issue by hhhaiai** [Tribler/self-compile-Android#6]
platform -> android-18.jar compiler -> ecj-4.5.jar dexer -> SDK\build-tools\23.0.0\lib\dx.jar apk build -> sdklib-24.3.4.jar signer -> zipsigner-lib-1.17.jar zipsigner-lib-optional-1.17.jar zipio-lib-1.8.jar kellinwood-loggin-lib-1.1.jar sc-core-1.52.0.0.jar sc-prov-1.52.0.0.jar sc-pkix-1.52.0.0.jar sc-pg-1.52.0.0.jar

this libs.

**Comment by synctext** [comment]
This university project has no active development.

We might pick up on this again in the future. Stealth capability is long-term requirement.

**Comment by hhhaiai** [comment]
> This university project has no active development.
> 
> We might pick up on this again in the future. Stealth capability is long-term requirement.

OK。 thx
